apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-v2
  labels:
    app: guestbook
    version: "2.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: guestbook
  template:
    metadata:
      name: guestbook-app-pod
      labels:
        app: guestbook
        version: "2.0"
    spec:
      containers:
        - name: guestbook
          image: kubernetes/guestbook:v2
          ports:
            - name: http
              containerPort: 3000